<?php

/**
 * Test class for yTrackingRegistry.
 * Generated by PHPUnit on 2011-07-23 at 23:21:40.
 */
class yTrackingRegistryTest extends PHPUnit_Framework_TestCase{
    /**
     * @var yTrackingRegistry
     */
    protected $object;
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(){
        
    }
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(){
        
    }
    public function testIsChanged(){
        $r = new yTrackingRegistry;
        $obj = array();
        $r['id'] = 2;
        $this->assertEquals(true, $r->isChanged());
        $this->assertEquals(array('id'), $r->getChangedKeys());
        $this->assertEquals(array('id'=>true), $r->getChangesMap());
        $r['id2'] = 3;
        $r['id'] = 4;
        $r[$obj] = 5;
        $this->assertEquals(true, $r->isChanged());
        $this->assertEquals(array('id', 'id2', 'Array'), $r->getChangedKeys());
        $this->assertEquals(array('id'=>true, 'id2'=>true, 'Array'=>true), $r->getChangesMap());
        $r->markUnchanged();
        $this->assertEquals(false, $r->isChanged());
        $this->assertEquals(array(), $r->getChangedKeys());
        $this->assertEquals(array(), $r->getChangesMap());
    }
}

