<?php

/**
 * Test class for yModelSql.
 * Generated by PHPUnit on 2011-07-23 at 14:14:17.
 */
class yModelSqlTest extends PHPUnit_Framework_TestCase{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(){
        
    }
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(){
        
    }
    public function testSome(){
        $posts = new yModelCollection('post');
        $query = new yModelQuery();
        $query->where($posts->id->is(new yModelQueryParameter('postId')));
        $postView = new yModelView($query);
        $postView->setName('post');
        $postView->postId[1];
        $postView(1);
        $query->where('postId', 1);
        $sql = new yModelSql($query);
        echo $sql;
    }
}

class postQuery extends yModelQuery{
    public function get($id){
        $posts = new yModelCollection('post');
        $post = $this->collection('post')->id->is($id)->fetch();
    }
}

class postQuery extends yModelQuery{
    public function __construct($id){
        $posts = new yModelCollection('post');
        $post = $posts->id->is($id)->fetch();
        parent::__construct($posts->id->is(new yModelQueryParameter('postId')));
    }
}

$posts = new postQuery();
$posts[1];

