<?php

/**
 * Test class for yModelExpression.
 * Generated by PHPUnit on 2011-07-23 at 14:01:01.
 */
class yModelExpressionTest extends PHPUnit_Framework_TestCase{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(){
        
    }
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(){
        
    }
    public function testGetLeft(){
        $e = new yModelExpression('a', 'b', 'c');
        $this->assertEquals('a', $e->getLeft());
    }
    public function testSetLeft(){
        $e = new yModelExpression('a', 'b', 'c');
        $e->setLeft('d');
        $this->assertEquals('d', $e->getLeft());
    }
    public function testGetRight(){
        $e = new yModelExpression('a', 'b', 'c');
        $this->assertEquals('c', $e->getRight());
    }
    public function testSetRight(){
        $e = new yModelExpression('a', 'b', 'c');
        $e->setRight('d');
        $this->assertEquals('d', $e->getRight());
    }
    public function testGetOperator(){
        $e = new yModelExpression('a', 'b', 'c');
        $this->assertEquals('b', $e->getOperator());
    }
    public function testSetOperator(){
        $e = new yModelExpression('a', 'b', 'c');
        $e->setOperator('d');
        $this->assertEquals('d', $e->getOperator());
    }
}
