<?php

/**
 * Test class for yModelOrder.
 * Generated by PHPUnit on 2011-07-23 at 23:18:00.
 */
class yModelOrderTest extends PHPUnit_Framework_TestCase{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(){
        
    }
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(){
        
    }
    public function testGetField(){
        $f = new yModelField('post', 'id');
        $o = new yModelOrder($f, 'asc');
        $this->assertEquals($f, $o->getField());
    }
    public function testGetDirection(){
        $f = new yModelField('post', 'id');
        $o = new yModelOrder($f, 'asc');
        $this->assertEquals('asc', $o->getDirection());
        $o = new yModelOrder($f);
        $this->assertEquals('asc', $o->getDirection());
        $o = new yModelOrder($f, 'desc');
        $this->assertEquals('desc', $o->getDirection());
    }
    public function testSetDirection(){
        $f = new yModelField('post', 'id');
        $o = new yModelOrder($f, 'asc');
        $o->setDirection('desc');
        $this->assertEquals('desc', $o->getDirection());
    }
    public function testSetField(){
        $f = new yModelField('post', 'id');
        $f2 = new yModelField('post2', 'id2');
        $o = new yModelOrder($f, 'asc');
        $o->setField($f2);
        $this->assertEquals($f2, $o->getField());
    }
}

