<?php

/**
 * Test class for yModelQueryParameter.
 * Generated by PHPUnit on 2011-08-04 at 23:57:20.
 */
class yModelQueryParameterTest extends PHPUnit_Framework_TestCase{
    /**
     * @var yModelQueryParameter
     */
    protected $object;
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(){
        
    }
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(){
        
    }
    public function testGetName(){
        $p = new yModelQueryParameter();
        $this->assertEquals(null, $p->getName());
        $p = new yModelQueryParameter('name');
        $this->assertEquals('name', $p->getName());
    }
    public function test__toString(){
        $p = new yModelQueryParameter();
        $this->assertEquals('', strval($p));
        $p = new yModelQueryParameter('name');
        $this->assertEquals('name', strval($p));
    }
}
