<?php

/**
 * Test class for yModelFunction.
 * Generated by PHPUnit on 2011-07-23 at 14:04:05.
 */
class yModelFunctionTest extends PHPUnit_Framework_TestCase{
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(){
        
    }
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown(){
        
    }
    public function testGetArguments(){
        $f = new yModelFunction('a', 'b');
        $this->assertEquals(array('b'), $f->getArguments());
    }
    public function testSetArguments(){
        $f = new yModelFunction('a', 'b');
        $f->setArguments(array('c', 'd'));
        $this->assertEquals(array('c', 'd'), $f->getArguments());
    }
    public function testGetFunction(){
        $f = new yModelFunction('a', 'b');
        $this->assertEquals('a', $f->getFunction());
    }
    public function testSetFunction(){
        $f = new yModelFunction('a', 'b');
        $f->setFunction('d');
        $this->assertEquals('d', $f->getFunction());
    }
}
